name: Manually triggered workflow - Updating file
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
        
env:
  FRONTEND_URL: ${{ github.event.inputs.name }}

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "Hello ${{ env.FRONTEND_URL }}"
        cat database.sql
    
    - uses: danielr1996/envsubst-action@1.1.0
      with:
        input: database.sql
        output: test.sql
    - run: |
        echo "Hello ${{ env.FRONTEND_URL }}"
        cat test.sql
    - run: |
        mkdir Database
        mv test.sql Database
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: Database

